In [2]:
import io
import pandas as pd

data='''Name|Age|color
Avneesh|19|Red
Jitesh|19|Yellow
Nitesh|19|Green
Prince|26|Pink'''

df=pd.read_table(io.StringIO(data), sep='|')
df

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green
3   Prince   26    Pink

# filter columns

In [3]:
df[['Name', 'Age']]

      Name  Age
0  Avneesh   19
1   Jitesh   19
2   Nitesh   19
3   Prince   26

In [9]:
mask=df.columns.str.startswith('A')
mask
df.iloc[:, mask]

   Age
0   19
1   19
2   19
3   26

# boolean array

In [10]:
df.Age>25

0    False
1    False
2    False
3     True
Name: Age, dtype: bool

In [11]:
df.Name.str.startswith('A')

0     True
1    False
2    False
3    False
Name: Name, dtype: bool

In [12]:
df

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green
3   Prince   26    Pink

# filtering rows

In [13]:
mask=df.Name.str.startswith('A')
df[mask]

      Name  Age color
0  Avneesh   19   Red

In [14]:
mask1=df.Age<23
df[mask1]

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green

In [15]:
mask1=df.Age<23
df[mask1]

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green

# using fuction to filter

In [16]:
df

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green
3   Prince   26    Pink

In [17]:
def is_prime(val):
    try:
        end=int(val/2)+1
    except ValueError:
        return False

    for i in range(2, end):
        if val%i==0:
            return False
    return True

In [21]:
is_prime(5)

True

In [22]:
mask=df.Age.apply(is_prime)
df[mask]

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green

In [23]:
def lt25(val):
    return val<25
mask1=df.Age.apply(lt25)
df[mask1]

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green

# boolean operation filter

In [25]:
mask=df.Name.str.startswith('A')
df[mask]

      Name  Age color
0  Avneesh   19   Red

In [26]:
mask2=df['Age']<25
df[mask2]

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green

In [27]:
df[mask & mask2]

      Name  Age color
0  Avneesh   19   Red

In [28]:
df[mask|mask2]

      Name  Age   color
0  Avneesh   19     Red
1   Jitesh   19  Yellow
2   Nitesh   19   Green

In [26]:
import pandas as pd
import numpy as np

df=pd.read_csv('superstore.csv')
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [34]:
df['Order.Date']=pd.to_datetime(df['Order.Date'])
df['Ship.Date']=pd.to_datetime(df['Ship.Date'])
df['Year']=pd.to_datetime(df['Year'])
df.dtypes
df

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,19,Consumer,2011-01-09,Second Class,4.37,California,Paper,1970-01-01 00:00:00.000002011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,19,Consumer,2011-01-26,Standard Class,0.94,California,Paper,1970-01-01 00:00:00.000002011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,21,Consumer,2011-08-09,Standard Class,1.81,California,Paper,1970-01-01 00:00:00.000002011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,111,Consumer,2011-08-09,Standard Class,4.59,California,Paper,1970-01-01 00:00:00.000002011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,6,Consumer,2011-10-03,Standard Class,1.32,California,Paper,1970-01-01 00:00:00.000002011,North America,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,69,Corporate,2014-12-04,Same Day,5.15,California,Binders,1970-01-01 00:00:00.000002014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,9,Corporate,2014-12-04,Same Day,0.44,California,Binders,1970-01-01 00:00:00.000002014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18,CA-2014-106964,...,12,Home Office,2014-12-21,First Class,0.31,California,Binders,1970-01-01 00:00:00.000002014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25,CA-2014-145219,...,90,Home Office,2014-12-26,First Class,15.95,California,Binders,1970-01-01 00:00:00.000002014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26,CA-2014-121398,...,154,Corporate,2014-12-30,Standard Class,9.59,California,Binders,1970-01-01 00:00:00.000002014,North America,52

In [35]:
df.shape[0]

51290

In [36]:
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [37]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,19,Consumer,2011-01-09,Second Class,4.37,California,Paper,1970-01-01 00:00:00.000002011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,19,Consumer,2011-01-26,Standard Class,0.94,California,Paper,1970-01-01 00:00:00.000002011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,21,Consumer,2011-08-09,Standard Class,1.81,California,Paper,1970-01-01 00:00:00.000002011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,111,Consumer,2011-08-09,Standard Class,4.59,California,Paper,1970-01-01 00:00:00.000002011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,6,Consumer,2011-10-03,Standard Class,1.32,California,Paper,1970-01-01 00:00:00.000002011,North America,40

In [38]:
df.tail()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,69,Corporate,2014-12-04,Same Day,5.15,California,Binders,1970-01-01 00:00:00.000002014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,9,Corporate,2014-12-04,Same Day,0.44,California,Binders,1970-01-01 00:00:00.000002014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18,CA-2014-106964,...,12,Home Office,2014-12-21,First Class,0.31,California,Binders,1970-01-01 00:00:00.000002014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25,CA-2014-145219,...,90,Home Office,2014-12-26,First Class,15.95,California,Binders,1970-01-01 00:00:00.000002014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26,CA-2014-121398,...,154,Corporate,2014-12-30,Standard Class,9.59,California,Binders,1970-01-01 00:00:00.000002014,North America,52

In [39]:
df=df.drop_duplicates()
print(df.duplicated().sum())

0

In [40]:
df.columns=df.columns.str.lower()
df

,category,city,country,customer.id,customer.name,discount,market,记录数,order.date,order.id,...,sales,segment,ship.date,ship.mode,shipping.cost,state,sub.category,year,market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,19,Consumer,2011-01-09,Second Class,4.37,California,Paper,1970-01-01 00:00:00.000002011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,19,Consumer,2011-01-26,Standard Class,0.94,California,Paper,1970-01-01 00:00:00.000002011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,21,Consumer,2011-08-09,Standard Class,1.81,California,Paper,1970-01-01 00:00:00.000002011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,111,Consumer,2011-08-09,Standard Class,4.59,California,Paper,1970-01-01 00:00:00.000002011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,6,Consumer,2011-10-03,Standard Class,1.32,California,Paper,1970-01-01 00:00:00.000002011,North America,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,69,Corporate,2014-12-04,Same Day,5.15,California,Binders,1970-01-01 00:00:00.000002014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,9,Corporate,2014-12-04,Same Day,0.44,California,Binders,1970-01-01 00:00:00.000002014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18,CA-2014-106964,...,12,Home Office,2014-12-21,First Class,0.31,California,Binders,1970-01-01 00:00:00.000002014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25,CA-2014-145219,...,90,Home Office,2014-12-26,First Class,15.95,California,Binders,1970-01-01 00:00:00.000002014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26,CA-2014-121398,...,154,Corporate,2014-12-30,Standard Class,9.59,California,Binders,1970-01-01 00:00:00.000002014,North America,52

In [41]:
df.columns=df.columns.str.lower()

In [42]:
df

,category,city,country,customer.id,customer.name,discount,market,记录数,order.date,order.id,...,sales,segment,ship.date,ship.mode,shipping.cost,state,sub.category,year,market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,19,Consumer,2011-01-09,Second Class,4.37,California,Paper,1970-01-01 00:00:00.000002011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,19,Consumer,2011-01-26,Standard Class,0.94,California,Paper,1970-01-01 00:00:00.000002011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,21,Consumer,2011-08-09,Standard Class,1.81,California,Paper,1970-01-01 00:00:00.000002011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,111,Consumer,2011-08-09,Standard Class,4.59,California,Paper,1970-01-01 00:00:00.000002011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,6,Consumer,2011-10-03,Standard Class,1.32,California,Paper,1970-01-01 00:00:00.000002011,North America,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,69,Corporate,2014-12-04,Same Day,5.15,California,Binders,1970-01-01 00:00:00.000002014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,9,Corporate,2014-12-04,Same Day,0.44,California,Binders,1970-01-01 00:00:00.000002014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18,CA-2014-106964,...,12,Home Office,2014-12-21,First Class,0.31,California,Binders,1970-01-01 00:00:00.000002014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25,CA-2014-145219,...,90,Home Office,2014-12-26,First Class,15.95,California,Binders,1970-01-01 00:00:00.000002014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26,CA-2014-121398,...,154,Corporate,2014-12-30,Standard Class,9.59,California,Binders,1970-01-01 00:00:00.000002014,North America,52

In [43]:
region_wise_sales=df.groupby('region')['sales'].sum()
region_wise_sales

region
Africa             783776
Canada              66932
Caribbean          324281
Central           2822399
Central Asia       752839
EMEA               806184
East               678834
North             1248192
North Asia         848349
Oceania           1100207
South             1600960
Southeast Asia     884438
West               725514
Name: sales, dtype: int64

In [44]:
category_avg_sales=df.groupby('category')['sales'].mean()
category_avg_sales

category
Furniture          416.249899
Office Supplies    121.105426
Technology         467.872103
Name: sales, dtype: float64

In [46]:
region_max_sales=df.groupby('region')['sales'].max().sort_values(ascending=False)
region_max_sales

region
South             22638
Central           17500
West              14000
East              11200
North Asia         6999
Oceania            6440
North              5785
Central Asia       5752
Africa             5301
EMEA               5211
Southeast Asia     4242
Canada             3864
Caribbean          2818
Name: sales, dtype: int64

In [50]:
region_and_category_sales=df.groupby(['region', 'category'])['sales'].sum()
region_and_category_sales

region          category
Africa          Furniture           194650
                Office Supplies     266752
                Technology          322374
Canada          Furniture            10595
                Office Supplies      30037
                Technology           26300
Caribbean       Furniture           118379
                Office Supplies      89565
                Technology          116337
Central         Furniture           860413
                Office Supplies     923471
                Technology         1038515
Central Asia    Furniture           284369
                Office Supplies     162768
                Technology          305702
EMEA            Furniture           228627
                Office Supplies     276712
                Technology          300845
East            Furniture           208291
                Office Supplies     205549
                Technology          264994
North           Furniture           377612
                Office Supplies     374778
                Technology          495802
North Asia      Furniture           335725
                Office Supplies     198581
                Technology          314043
Oceania         Furniture           410473
                Office Supplies     281729
                Technology          408005
South           Furniture           515739
                Office Supplies     515208
                Technology          570013
Southeast Asia  Furniture           313391
                Office Supplies     241299
                Technology          329748
West            Furniture           252620
                Office Supplies     220881
                Technology          252013
Name: sales, dtype: int64

In [63]:
df['new_year']=df['order.date'].dt.year
year

0        2011
1        2011
2        2011
3        2011
4        2011
         ...
51285    2014
51286    2014
51287    2014
51288    2014
51289    2014
Name: order.date, Length: 51290, dtype: int32

In [60]:
df['month']=df['order.date'].dt.month_name()
month

0          January
1          January
2           August
3           August
4        September
           ...
51285     December
51286     December
51287     December
51288     December
51289     December
Name: order.date, Length: 51290, dtype: object

In [62]:
month_wise_sales=df.groupby('month')['sales'].sum()
month_wise_sales

month
April         698603
August       1293852
December     1580816
February      543768
January       675141
July          749423
June         1269751
March         770519
May           904061
November     1551319
October      1168220
September    1437432
Name: sales, dtype: int64

In [64]:
year_wise_total_sales=df.groupby('new_year')['sales'].sum()
year_wise_total_sales

new_year
2011    2259511
2012    2677493
2013    3405860
2014    4300041
Name: sales, dtype: int64

In [73]:
df['total_sales']=df['sales']*df['quantity']
df['total_sales']

df['new_segment']=df['total_sales'].apply(lambda x: 'High' if x>100 else 'low')
df['new_segment']

0         low
1         low
2         low
3        High
4         low
         ...
51285    High
51286     low
51287     low
51288    High
51289    High
Name: new_segment, Length: 51290, dtype: object

In [78]:
pivot1=pd.pivot_table(
    df,
    index='region',
    columns='category',
    values='sales',
    aggfunc='sum'
)

pivot1

category        Furniture  Office Supplies  Technology
region
Africa             194650           266752      322374
Canada              10595            30037       26300
Caribbean          118379            89565      116337
Central            860413           923471     1038515
Central Asia       284369           162768      305702
EMEA               228627           276712      300845
East               208291           205549      264994
North              377612           374778      495802
North Asia         335725           198581      314043
Oceania            410473           281729      408005
South              515739           515208      570013
Southeast Asia     313391           241299      329748
West               252620           220881      252013